version: "3"
services:
  ui-service:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - ui-service
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
    restart: unless-stopped

networks:
  ui-service:
    driver: bridge
